// The sole registry of shipped components. Keep import paths literal so publication
// and TypeScript can resolve the module graph. No shader evaluates until requested;
// normal module caching shares family shaders with direct and eager imports.
const loaders = {
    lastStand: () => import("./lastStand.ts"),
    victoryStamp: () => import("./victoryStamp.ts"),
    focusLock: () => import("./focusLock.ts"),
    rebound: () => import("./rebound.ts"),
    ricochet: () => import("./ricochet.ts"),
    overdrive: () => import("./overdrive.ts"),
    aftershock: () => import("./aftershock.ts"),
    crosscut: () => import("./crosscut.ts"),
    knockback: () => import("./knockback.ts"),
    unarmed: () => import("./unarmed.ts"),
    eventHorizon: () => import("./eventHorizon.ts"),
    dragonBreath: () => import("./dragonBreath.ts"),
    vanish: () => import("./vanish.ts"),
    psionic: () => import("./psionic.ts"),
    weightPulse: () => import("./weightPulse.ts"),
    decay: () => import("./decay.ts"),
    lava: () => import("./lava.ts"),
    crystal: () => import("./crystal.ts"),
    vitalSign: () => import("./vitalSign.ts"),
    echoFrame: () => import("./echoFrame.ts"),
    alarm: () => import("./alarm.ts"),
    prismSweep: () => import("./prismSweep.ts"),
    cometCall: () => import("./cometCall.ts"),
    beacon: () => import("./beacon.ts"),
    converge: () => import("./converge.ts"),
    sonar: () => import("./sonar.ts"),
    phoenixRebirth: () => import("./phoenixRebirth.ts"),
    astralConjunction: () => import("./astralConjunction.ts"),
    interruptNow: () => import("./interruptNow.ts"),
    spatialStitch: () => import("./spatialStitch.ts"),
    poisoned: () => import("./poisoned.ts"),
    charm: () => import("./charm.ts"),
    geas: () => import("./geas.ts"),
    verdant: () => import("./verdant.ts"),
    stoneSkin: () => import("./stoneSkin.ts"),
    gilding: () => import("./gilding.ts"),
    silence: () => import("./silence.ts"),
    possession: () => import("./possession.ts"),
    trueSight: () => import("./trueSight.ts"),
    forgetting: () => import("./forgetting.ts"),
    soulDrain: () => import("./soulDrain.ts"),
    mycelium: () => import("./mycelium.ts"),
    barkMend: () => import("./barkMend.ts"),
    ritualKnot: () => import("./ritualKnot.ts"),
    counterSeal: () => import("./counterSeal.ts"),
    voidBloom: () => import("./voidBloom.ts"),
    watchers: () => import("./watchers.ts"),
    spellSeal: () => import("./spellSeal.ts"),
    leyWeave: () => import("./leyWeave.ts"),
    elderSign: () => import("./elderSign.ts"),
    autumn: () => import("./autumn.ts"),
    rootbind: () => import("./rootbind.ts"),
    eldritchEcho: () => import("./eldritchEcho.ts"),
    aberration: () => import("./aberration.ts"),
    blackTide: () => import("./blackTide.ts"),
    shatter: () => import("./shatter.ts"),
    unravel: () => import("./unravel.ts"),
    liquefy: () => import("./liquefy.ts"),
    inkBloom: () => import("./inkBloom.ts"),
    duel: () => import("./duel.ts"),
    eclipse: () => import("./eclipse.ts"),
    dimensionalRift: () => import("./dimensionalRift.ts"),
    shockfront: () => import("./shockfront.ts"),
    judgement: () => import("./judgement.ts"),
    ascension: () => import("./ascension.ts"),
    wind: () => import("./wind.ts"),
    sand: () => import("./sand.ts"),
    recoil: () => import("./recoil.ts"),
    accordion: () => import("./accordion.ts"),
    pendulum: () => import("./pendulum.ts"),
    domino: () => import("./domino.ts"),
    tumble: () => import("./tumble.ts"),
    magnetic: () => import("./magnetic.ts"),
    vortex: () => import("./vortex.ts"),
    tide: () => import("./tide.ts"),
    elastic: () => import("./elastic.ts"),
    quake: () => import("./quake.ts"),
    explode: () => import("./explode.ts"),
    implode: () => import("./implode.ts"),
    emphasis: () => import("./emphasis.ts"),
    fire: () => import("./fire.ts"),
    smoke: () => import("./smoke.ts"),
    reverseSmoke: () => import("./reverseSmoke.ts"),
    electricity: () => import("./electricity.ts"),
    lightning: () => import("./lightning.ts"),
    poisonCloud: () => import("./poisonCloud.ts"),
    healingCloud: () => import("./healingCloud.ts"),
    frost: () => import("./frost.ts"),
    ward: () => import("./ward.ts"),
    impact: () => import("./impact.ts"),
    animeImpact: () => import("./animeImpact.ts"),
    holyGleam: () => import("./holyGleam.ts"),
    acid: () => import("./acid.ts"),
    spectral: () => import("./spectral.ts"),
    swarm: () => import("./swarm.ts"),
    thorns: () => import("./thorns.ts"),
    slash: () => import("./slash.ts"),
    critical: () => import("./critical.ts"),
    parry: () => import("./parry.ts"),
    healWave: () => import("./healWave.ts"),
    blessing: () => import("./blessing.ts"),
    teleport: () => import("./teleport.ts"),
    cleave: () => import("./cleave.ts"),
    riposte: () => import("./riposte.ts"),
    dispel: () => import("./dispel.ts"),
    divineShield: () => import("./divineShield.ts"),
    fireflies: () => import("./fireflies.ts"),
    runicOrbit: () => import("./runicOrbit.ts"),
    radiate: () => import("./radiate.ts"),
    greeting: () => import("./greeting.ts"),
    hostile: () => import("./hostile.ts"),
    dread: () => import("./dread.ts"),
    quest: () => import("./quest.ts"),
    levelUp: () => import("./levelUp.ts"),
    healNeeded: () => import("./healNeeded.ts"),
    expiring: () => import("./expiring.ts"),
    rally: () => import("./rally.ts"),
    discovery: () => import("./discovery.ts"),
} as const;

export type EffectName = keyof typeof loaders;
export type EffectMap = { [K in EffectName]: Awaited<ReturnType<(typeof loaders)[K]>>["default"] };
export const effectNames = Object.freeze(Object.keys(loaders) as EffectName[]);

/** Load one component before using it in synchronous JSX. Imports reuse the module cache. */
export async function loadEffect<K extends EffectName>(name: K): Promise<EffectMap[K]> {
    if (!Object.prototype.hasOwnProperty.call(loaders, name)) throw new TypeError(`Unknown text effect: ${name}`);
    return (await loaders[name]()).default as EffectMap[K];
}

/** Explicitly preload a chosen set; the returned object retains each component's own prop types. */
export async function loadEffects<const N extends readonly EffectName[]>(names: N): Promise<Readonly<Pick<EffectMap, N[number]>>> {
    const entries = await Promise.all(names.map(async name => [name, await loadEffect(name)] as const));
    return Object.freeze(Object.fromEntries(entries)) as Readonly<Pick<EffectMap, N[number]>>;
}
