[package]
name = "smudgy_map_widget"
version = "0.5.7-ptb2"
edition = "2024"

[dependencies]
iced = { workspace = true }
iced_anim = { workspace = true }
log = { workspace = true }
smudgy_cloud = { workspace = true }
smudgy_theme = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

