[package]
name = "smudgy_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
encoding_rs = "0.8"
flate2 = "1"
regex = { workspace = true }
smudgy_protocol = { workspace = true }
smudgy_session_model = { workspace = true }
vtparse = { workspace = true }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "terminal_buffer"
harness = false

[lints]
workspace = true
