[package]
name = "smudgy_session_model"
version = "0.5.8-dev"
edition = "2024"

[dependencies]
web-time = "1"
derive_more = { workspace = true }
log = { workspace = true }
serde = { workspace = true, features = ["rc"] }
thiserror = "2.0.12"
serde_json = { workspace = true }
naga = { version = "=27.0.3", features = ["wgsl-in"] }

[lints]
workspace = true

[dev-dependencies]
serde_json = { workspace = true }
