[package]
name = "smudgy_audio_web"
version = "0.5.7-ptb.5"
edition = "2024"
publish = false

[dependencies]
deno_audio = { workspace = true }
deno_error = { workspace = true }
smudgy_audio = { workspace = true }

[dev-dependencies]
assert_no_alloc = "1.1.2"
futures = { workspace = true }
smudgy_audio = { workspace = true, features = ["test-support"] }
web-audio-api = { git = "https://github.com/smudgy-mud/web-audio-api-rs", rev = "13ffdcd0f6c3472526653516f52a9320ef77a893", default-features = false }

[lints]
workspace = true
